version: 0.0
os: linux
files:
  - source: /target/embedded-0.0.1-SNAPSHOT.jar
    destination: /var/www/html/dist/
 # - source: /scripts/configure_http_port.xsl  embedded-0.0.1-SNAPSHOT.jar
 #   destination: //tmp/codedeploy-deployment-staging-areaa/
#hooks:
#  ApplicationStop:
 #   - location: scripts/stop_applicationn
  #    timeout: 300
 # BeforeInstall:
  #  - location: scripts/install_dependencies
  #    timeout: 300
  #ApplicationStart:
   # - location: scripts/write_codedeploy_config.sh
  #  - location: scripts/start_application
  #    timeout: 300
 # ValidateService:
  #  - location: scripts/basic_health_check.sh
