server:
  port: 8089

spring:
  #h2:
   # console:
    #  enabled: true
     # path: /h2-console
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mysql://bt-app-db.cowu1fm2skri.eu-west-2.rds.amazonaws.com:3306/iotpcf?useSSL=false
    username: admin
    password: adminadmin
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
